patch from all other branches because git was broken
FoilHatGuy/url_shortener_go_practice pull request #8
Opened 2023-02-01 11:37 UTC by FoilHatGuy

Гит сломался поэтому я все изменения перенес из других веток. Все изменения и коммиты сохранены в них, эта ветка содержит только совокупность изменений. И вообще, надо нормально писать задание, потому что там было написано "ветку с инкрементом можно мержить когда она доделана и скидывать куратору только последний пулл реквест"

2023-02-01 20:04 UTC, molchalin requested changes

2023-02-01 20:04 UTC, molchalin commented on internal/handlers/handlers.go
> +		} else {
А если запись не найдена?

2023-02-01 20:04 UTC, molchalin commented on internal/handlers/handlers.go
> +	fmt.Printf("Input url: %s\n", url)
```go
if len(url) != urlLength {
    w.WriteHeader(http.StatusBadRequest)
    return
}

url, err := storage.Database.GetURL(url)
// ...
```

2023-02-01 20:04 UTC, molchalin commented on internal/handlers/handlers_test.go
> +		//{
Нету позитивного теста на гет

2023-02-01 20:04 UTC, molchalin commented on internal/storage/temporary.go
> +type storage struct {
Давай абстрагируем взаимодействие с БД при помощи интерфейса

2023-02-02 07:58 UTC, FoilHatGuy commented on internal/handlers/handlers.go
> +		} else {
То тогда вернется Bad Request, это будет после else

2023-02-02 08:01 UTC, FoilHatGuy commented on internal/handlers/handlers_test.go
> +		//{
Позитивный тест get должен сначала положить данные в базу, но я не знаю как проверить что вернулось все верно потому что он сразу же перенаправляет на эту самую ссылку, которую я  в него записал. мне приходит 200 от google.com

2023-02-04 09:20 UTC, merged